theme: jekyll-theme-minimal
title: Liangjie Wu
show_downloads: true
description: Welcome! I am an Assistant Professor at Einaudi Institute for Economics and Finance. I received my PhD in Economics from the University of Chicago in June 2020. I am interested in search theory and the study of market power.
site.logo: true
