theme: jekyll-theme-minimal
title: Liangjie Wu
description: Welcome! I'm a PhD candidate in Economics at the University of Chicago. I am interested in search theory and the study of market power. I will join the Einaudi Institute for Economics and Finance as an Assistant Professor in Fall 2020. 
logo: https://github.com/liangjiewu123/liangjiewu.github.io/blob/master/files/DSCN7356.JPG
